// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/cristianoliveira/other/aerospace-ipc/pkg/aerospace/workspaces/workspaces.go
//
// Generated by this command:
//
//	mockgen -source=/Users/cristianoliveira/other/aerospace-ipc/pkg/aerospace/workspaces/workspaces.go -destination=/Users/cristianoliveira/other/aerospace-ipc/mocks/aerospace/workspaces/workspaces_mock.go -package=workspaces_mock
//

// Package workspaces_mock is a generated GoMock package.
package workspaces_mock

import (
	reflect "reflect"

	workspaces "github.com/cristianoliveira/aerospace-ipc/pkg/aerospace/workspaces"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspacesService is a mock of WorkspacesService interface.
type MockWorkspacesService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspacesServiceMockRecorder
	isgomock struct{}
}

// MockWorkspacesServiceMockRecorder is the mock recorder for MockWorkspacesService.
type MockWorkspacesServiceMockRecorder struct {
	mock *MockWorkspacesService
}

// NewMockWorkspacesService creates a new mock instance.
func NewMockWorkspacesService(ctrl *gomock.Controller) *MockWorkspacesService {
	mock := &MockWorkspacesService{ctrl: ctrl}
	mock.recorder = &MockWorkspacesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspacesService) EXPECT() *MockWorkspacesServiceMockRecorder {
	return m.recorder
}

// GetFocusedWorkspace mocks base method.
func (m *MockWorkspacesService) GetFocusedWorkspace() (*workspaces.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFocusedWorkspace")
	ret0, _ := ret[0].(*workspaces.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFocusedWorkspace indicates an expected call of GetFocusedWorkspace.
func (mr *MockWorkspacesServiceMockRecorder) GetFocusedWorkspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFocusedWorkspace", reflect.TypeOf((*MockWorkspacesService)(nil).GetFocusedWorkspace))
}

// MoveWindowToWorkspace mocks base method.
func (m *MockWorkspacesService) MoveWindowToWorkspace(args workspaces.MoveWindowToWorkspaceArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveWindowToWorkspace", args)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveWindowToWorkspace indicates an expected call of MoveWindowToWorkspace.
func (mr *MockWorkspacesServiceMockRecorder) MoveWindowToWorkspace(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveWindowToWorkspace", reflect.TypeOf((*MockWorkspacesService)(nil).MoveWindowToWorkspace), args)
}

// MoveWindowToWorkspaceWithOpts mocks base method.
func (m *MockWorkspacesService) MoveWindowToWorkspaceWithOpts(args workspaces.MoveWindowToWorkspaceArgs, opts workspaces.MoveWindowToWorkspaceOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveWindowToWorkspaceWithOpts", args, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveWindowToWorkspaceWithOpts indicates an expected call of MoveWindowToWorkspaceWithOpts.
func (mr *MockWorkspacesServiceMockRecorder) MoveWindowToWorkspaceWithOpts(args, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveWindowToWorkspaceWithOpts", reflect.TypeOf((*MockWorkspacesService)(nil).MoveWindowToWorkspaceWithOpts), args, opts)
}
