// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/cristianoliveira/other/aerospace-ipc/pkg/aerospace/focus/focus.go
//
// Generated by this command:
//
//	mockgen -source=/Users/cristianoliveira/other/aerospace-ipc/pkg/aerospace/focus/focus.go -destination=mocks/aerospace/focus/focus_mock.go -package=focus_mock
//

// Package focus_mock is a generated GoMock package.
package focus_mock

import (
	reflect "reflect"

	focus "github.com/cristianoliveira/aerospace-ipc/pkg/aerospace/focus"
	gomock "go.uber.org/mock/gomock"
)

// MockFocusService is a mock of FocusService interface.
type MockFocusService struct {
	ctrl     *gomock.Controller
	recorder *MockFocusServiceMockRecorder
	isgomock struct{}
}

// MockFocusServiceMockRecorder is the mock recorder for MockFocusService.
type MockFocusServiceMockRecorder struct {
	mock *MockFocusService
}

// NewMockFocusService creates a new mock instance.
func NewMockFocusService(ctrl *gomock.Controller) *MockFocusService {
	mock := &MockFocusService{ctrl: ctrl}
	mock.recorder = &MockFocusServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFocusService) EXPECT() *MockFocusServiceMockRecorder {
	return m.recorder
}

// SetFocusByDFS mocks base method.
func (m *MockFocusService) SetFocusByDFS(direction string, opts ...focus.SetFocusOpts) error {
	m.ctrl.T.Helper()
	varargs := []any{direction}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetFocusByDFS", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByDFS indicates an expected call of SetFocusByDFS.
func (mr *MockFocusServiceMockRecorder) SetFocusByDFS(direction any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{direction}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByDFS", reflect.TypeOf((*MockFocusService)(nil).SetFocusByDFS), varargs...)
}

// SetFocusByDFSIndex mocks base method.
func (m *MockFocusService) SetFocusByDFSIndex(dfsIndex int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocusByDFSIndex", dfsIndex)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByDFSIndex indicates an expected call of SetFocusByDFSIndex.
func (mr *MockFocusServiceMockRecorder) SetFocusByDFSIndex(dfsIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByDFSIndex", reflect.TypeOf((*MockFocusService)(nil).SetFocusByDFSIndex), dfsIndex)
}

// SetFocusByDirection mocks base method.
func (m *MockFocusService) SetFocusByDirection(direction string, opts ...focus.SetFocusOpts) error {
	m.ctrl.T.Helper()
	varargs := []any{direction}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetFocusByDirection", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByDirection indicates an expected call of SetFocusByDirection.
func (mr *MockFocusServiceMockRecorder) SetFocusByDirection(direction any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{direction}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByDirection", reflect.TypeOf((*MockFocusService)(nil).SetFocusByDirection), varargs...)
}

// SetFocusByWindowID mocks base method.
func (m *MockFocusService) SetFocusByWindowID(windowID int, opts ...focus.SetFocusOpts) error {
	m.ctrl.T.Helper()
	varargs := []any{windowID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetFocusByWindowID", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByWindowID indicates an expected call of SetFocusByWindowID.
func (mr *MockFocusServiceMockRecorder) SetFocusByWindowID(windowID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{windowID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByWindowID", reflect.TypeOf((*MockFocusService)(nil).SetFocusByWindowID), varargs...)
}
