// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/aerospace/monitors/monitors.go
//
// Generated by this command:
//
//	mockgen -source=pkg/aerospace/monitors/monitors.go -destination=mocks/aerospace/monitors/monitors_mock.go -package=monitors_mock
//

// Package monitors_mock is a generated GoMock package.
package monitors_mock

import (
	reflect "reflect"

	monitors "github.com/cristianoliveira/aerospace-ipc/pkg/aerospace/monitors"
	gomock "go.uber.org/mock/gomock"
)

// MockMonitorsService is a mock of MonitorsService interface.
type MockMonitorsService struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorsServiceMockRecorder
	isgomock struct{}
}

// MockMonitorsServiceMockRecorder is the mock recorder for MockMonitorsService.
type MockMonitorsServiceMockRecorder struct {
	mock *MockMonitorsService
}

// NewMockMonitorsService creates a new mock instance.
func NewMockMonitorsService(ctrl *gomock.Controller) *MockMonitorsService {
	mock := &MockMonitorsService{ctrl: ctrl}
	mock.recorder = &MockMonitorsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorsService) EXPECT() *MockMonitorsServiceMockRecorder {
	return m.recorder
}

// GetFocusedMonitor mocks base method.
func (m *MockMonitorsService) GetFocusedMonitor() (*monitors.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFocusedMonitor")
	ret0, _ := ret[0].(*monitors.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFocusedMonitor indicates an expected call of GetFocusedMonitor.
func (mr *MockMonitorsServiceMockRecorder) GetFocusedMonitor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFocusedMonitor", reflect.TypeOf((*MockMonitorsService)(nil).GetFocusedMonitor))
}
