// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/aerospace/layout/layout.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/aerospace/layout/layout.go -destination=./mocks/aerospace/layout/layout_mock.go -package=layout_mock
//

// Package layout_mock is a generated GoMock package.
package layout_mock

import (
	reflect "reflect"

	layout "github.com/cristianoliveira/aerospace-ipc/pkg/aerospace/layout"
	gomock "go.uber.org/mock/gomock"
)

// MockLayoutService is a mock of LayoutService interface.
type MockLayoutService struct {
	ctrl     *gomock.Controller
	recorder *MockLayoutServiceMockRecorder
	isgomock struct{}
}

// MockLayoutServiceMockRecorder is the mock recorder for MockLayoutService.
type MockLayoutServiceMockRecorder struct {
	mock *MockLayoutService
}

// NewMockLayoutService creates a new mock instance.
func NewMockLayoutService(ctrl *gomock.Controller) *MockLayoutService {
	mock := &MockLayoutService{ctrl: ctrl}
	mock.recorder = &MockLayoutServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLayoutService) EXPECT() *MockLayoutServiceMockRecorder {
	return m.recorder
}

// SetLayout mocks base method.
func (m *MockLayoutService) SetLayout(layouts []string, opts ...layout.SetLayoutOpts) error {
	m.ctrl.T.Helper()
	varargs := []any{layouts}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetLayout", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLayout indicates an expected call of SetLayout.
func (mr *MockLayoutServiceMockRecorder) SetLayout(layouts any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{layouts}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLayout", reflect.TypeOf((*MockLayoutService)(nil).SetLayout), varargs...)
}
