// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/cristianoliveira/other/aerospace-ipc/pkg/aerospace/windows/windows.go
//
// Generated by this command:
//
//	mockgen -source=/Users/cristianoliveira/other/aerospace-ipc/pkg/aerospace/windows/windows.go -destination=/Users/cristianoliveira/other/aerospace-ipc/mocks/aerospace/windows/windows_mock.go -package=windows_mock
//

// Package windows_mock is a generated GoMock package.
package windows_mock

import (
	reflect "reflect"

	windows "github.com/cristianoliveira/aerospace-ipc/pkg/aerospace/windows"
	gomock "go.uber.org/mock/gomock"
)

// MockWindowsService is a mock of WindowsService interface.
type MockWindowsService struct {
	ctrl     *gomock.Controller
	recorder *MockWindowsServiceMockRecorder
	isgomock struct{}
}

// MockWindowsServiceMockRecorder is the mock recorder for MockWindowsService.
type MockWindowsServiceMockRecorder struct {
	mock *MockWindowsService
}

// NewMockWindowsService creates a new mock instance.
func NewMockWindowsService(ctrl *gomock.Controller) *MockWindowsService {
	mock := &MockWindowsService{ctrl: ctrl}
	mock.recorder = &MockWindowsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindowsService) EXPECT() *MockWindowsServiceMockRecorder {
	return m.recorder
}

// GetAllWindows mocks base method.
func (m *MockWindowsService) GetAllWindows() ([]windows.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWindows")
	ret0, _ := ret[0].([]windows.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWindows indicates an expected call of GetAllWindows.
func (mr *MockWindowsServiceMockRecorder) GetAllWindows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWindows", reflect.TypeOf((*MockWindowsService)(nil).GetAllWindows))
}

// GetAllWindowsByWorkspace mocks base method.
func (m *MockWindowsService) GetAllWindowsByWorkspace(workspaceName string) ([]windows.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWindowsByWorkspace", workspaceName)
	ret0, _ := ret[0].([]windows.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWindowsByWorkspace indicates an expected call of GetAllWindowsByWorkspace.
func (mr *MockWindowsServiceMockRecorder) GetAllWindowsByWorkspace(workspaceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWindowsByWorkspace", reflect.TypeOf((*MockWindowsService)(nil).GetAllWindowsByWorkspace), workspaceName)
}

// GetFocusedWindow mocks base method.
func (m *MockWindowsService) GetFocusedWindow() (*windows.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFocusedWindow")
	ret0, _ := ret[0].(*windows.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFocusedWindow indicates an expected call of GetFocusedWindow.
func (mr *MockWindowsServiceMockRecorder) GetFocusedWindow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFocusedWindow", reflect.TypeOf((*MockWindowsService)(nil).GetFocusedWindow))
}

// SetFocusByDFS mocks base method.
func (m *MockWindowsService) SetFocusByDFS(args windows.SetFocusByDFSArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocusByDFS", args)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByDFS indicates an expected call of SetFocusByDFS.
func (mr *MockWindowsServiceMockRecorder) SetFocusByDFS(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByDFS", reflect.TypeOf((*MockWindowsService)(nil).SetFocusByDFS), args)
}

// SetFocusByDFSIndex mocks base method.
func (m *MockWindowsService) SetFocusByDFSIndex(args windows.SetFocusByDFSIndexArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocusByDFSIndex", args)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByDFSIndex indicates an expected call of SetFocusByDFSIndex.
func (mr *MockWindowsServiceMockRecorder) SetFocusByDFSIndex(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByDFSIndex", reflect.TypeOf((*MockWindowsService)(nil).SetFocusByDFSIndex), args)
}

// SetFocusByDFSWithOpts mocks base method.
func (m *MockWindowsService) SetFocusByDFSWithOpts(args windows.SetFocusByDFSArgs, opts windows.SetFocusByDFSOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocusByDFSWithOpts", args, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByDFSWithOpts indicates an expected call of SetFocusByDFSWithOpts.
func (mr *MockWindowsServiceMockRecorder) SetFocusByDFSWithOpts(args, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByDFSWithOpts", reflect.TypeOf((*MockWindowsService)(nil).SetFocusByDFSWithOpts), args, opts)
}

// SetFocusByDirection mocks base method.
func (m *MockWindowsService) SetFocusByDirection(args windows.SetFocusByDirectionArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocusByDirection", args)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByDirection indicates an expected call of SetFocusByDirection.
func (mr *MockWindowsServiceMockRecorder) SetFocusByDirection(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByDirection", reflect.TypeOf((*MockWindowsService)(nil).SetFocusByDirection), args)
}

// SetFocusByDirectionWithOpts mocks base method.
func (m *MockWindowsService) SetFocusByDirectionWithOpts(args windows.SetFocusByDirectionArgs, opts windows.SetFocusByDirectionOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocusByDirectionWithOpts", args, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByDirectionWithOpts indicates an expected call of SetFocusByDirectionWithOpts.
func (mr *MockWindowsServiceMockRecorder) SetFocusByDirectionWithOpts(args, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByDirectionWithOpts", reflect.TypeOf((*MockWindowsService)(nil).SetFocusByDirectionWithOpts), args, opts)
}

// SetFocusByWindowID mocks base method.
func (m *MockWindowsService) SetFocusByWindowID(args windows.SetFocusArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocusByWindowID", args)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByWindowID indicates an expected call of SetFocusByWindowID.
func (mr *MockWindowsServiceMockRecorder) SetFocusByWindowID(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByWindowID", reflect.TypeOf((*MockWindowsService)(nil).SetFocusByWindowID), args)
}

// SetFocusByWindowIDWithOpts mocks base method.
func (m *MockWindowsService) SetFocusByWindowIDWithOpts(args windows.SetFocusArgs, opts windows.SetFocusOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocusByWindowIDWithOpts", args, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByWindowIDWithOpts indicates an expected call of SetFocusByWindowIDWithOpts.
func (mr *MockWindowsServiceMockRecorder) SetFocusByWindowIDWithOpts(args, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByWindowIDWithOpts", reflect.TypeOf((*MockWindowsService)(nil).SetFocusByWindowIDWithOpts), args, opts)
}

// SetLayout mocks base method.
func (m *MockWindowsService) SetLayout(args windows.SetLayoutArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLayout", args)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLayout indicates an expected call of SetLayout.
func (mr *MockWindowsServiceMockRecorder) SetLayout(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLayout", reflect.TypeOf((*MockWindowsService)(nil).SetLayout), args)
}

// SetLayoutWithOpts mocks base method.
func (m *MockWindowsService) SetLayoutWithOpts(args windows.SetLayoutArgs, opts windows.SetLayoutOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLayoutWithOpts", args, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLayoutWithOpts indicates an expected call of SetLayoutWithOpts.
func (mr *MockWindowsServiceMockRecorder) SetLayoutWithOpts(args, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLayoutWithOpts", reflect.TypeOf((*MockWindowsService)(nil).SetLayoutWithOpts), args, opts)
}
