// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/cristianoliveira/other/aerospace-ipc/pkg/aerospace/windows/windows.go
//
// Generated by this command:
//
//	mockgen -source=/Users/cristianoliveira/other/aerospace-ipc/pkg/aerospace/windows/windows.go -destination=/Users/cristianoliveira/other/aerospace-ipc/mocks/aerospace/windows/windows_mock.go -package=windows_mock
//

// Package windows_mock is a generated GoMock package.
package windows_mock

import (
	reflect "reflect"

	windows "github.com/cristianoliveira/aerospace-ipc/pkg/aerospace/windows"
	gomock "go.uber.org/mock/gomock"
)

// MockWindowsService is a mock of WindowsService interface.
type MockWindowsService struct {
	ctrl     *gomock.Controller
	recorder *MockWindowsServiceMockRecorder
	isgomock struct{}
}

// MockWindowsServiceMockRecorder is the mock recorder for MockWindowsService.
type MockWindowsServiceMockRecorder struct {
	mock *MockWindowsService
}

// NewMockWindowsService creates a new mock instance.
func NewMockWindowsService(ctrl *gomock.Controller) *MockWindowsService {
	mock := &MockWindowsService{ctrl: ctrl}
	mock.recorder = &MockWindowsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindowsService) EXPECT() *MockWindowsServiceMockRecorder {
	return m.recorder
}

// GetAllWindows mocks base method.
func (m *MockWindowsService) GetAllWindows() ([]windows.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWindows")
	ret0, _ := ret[0].([]windows.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWindows indicates an expected call of GetAllWindows.
func (mr *MockWindowsServiceMockRecorder) GetAllWindows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWindows", reflect.TypeOf((*MockWindowsService)(nil).GetAllWindows))
}

// GetAllWindowsByWorkspace mocks base method.
func (m *MockWindowsService) GetAllWindowsByWorkspace(workspaceName string) ([]windows.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWindowsByWorkspace", workspaceName)
	ret0, _ := ret[0].([]windows.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWindowsByWorkspace indicates an expected call of GetAllWindowsByWorkspace.
func (mr *MockWindowsServiceMockRecorder) GetAllWindowsByWorkspace(workspaceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWindowsByWorkspace", reflect.TypeOf((*MockWindowsService)(nil).GetAllWindowsByWorkspace), workspaceName)
}

// GetFocusedWindow mocks base method.
func (m *MockWindowsService) GetFocusedWindow() (*windows.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFocusedWindow")
	ret0, _ := ret[0].(*windows.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFocusedWindow indicates an expected call of GetFocusedWindow.
func (mr *MockWindowsServiceMockRecorder) GetFocusedWindow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFocusedWindow", reflect.TypeOf((*MockWindowsService)(nil).GetFocusedWindow))
}

// SetFocusByWindowID mocks base method.
func (m *MockWindowsService) SetFocusByWindowID(windowID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocusByWindowID", windowID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFocusByWindowID indicates an expected call of SetFocusByWindowID.
func (mr *MockWindowsServiceMockRecorder) SetFocusByWindowID(windowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocusByWindowID", reflect.TypeOf((*MockWindowsService)(nil).SetFocusByWindowID), windowID)
}

// SetLayout mocks base method.
func (m *MockWindowsService) SetLayout(windowID int, layout string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLayout", windowID, layout)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLayout indicates an expected call of SetLayout.
func (mr *MockWindowsServiceMockRecorder) SetLayout(windowID, layout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLayout", reflect.TypeOf((*MockWindowsService)(nil).SetLayout), windowID, layout)
}
